//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinViewer.Strings.ru_RU {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BinViewer.Strings.ru_RU.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Архитектурные особенности:.
        /// </summary>
        public static string AboutArch_Text {
            get {
                return ResourceManager.GetString("AboutArch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Модификации хранятся изолированно в ОЗУ и не повреждают исходный файл до сохранения..
        /// </summary>
        public static string AboutArch1_Text {
            get {
                return ResourceManager.GetString("AboutArch1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Потокобезопасный асинхронный поиск блоками по 64 КБ..
        /// </summary>
        public static string AboutArch2_Text {
            get {
                return ResourceManager.GetString("AboutArch2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Автоматическое создание бэкапа (.bak) перед каждой записью для 100% защиты от потери данных..
        /// </summary>
        public static string AboutArch3_Text {
            get {
                return ResourceManager.GetString("AboutArch3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высокоскоростной профессиональный шестнадцатеричный редактор, спроектированный для мгновенного открытия файлов любого объема (от нескольких байт до сотен гигабайт). Приложение использует концепцию виртуализации потоков данных и UI элементов, за счет чего экономит ОЗУ и сохраняет максимальный FPS при скроллинге..
        /// </summary>
        public static string AboutDesc_Text {
            get {
                return ResourceManager.GetString("AboutDesc.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разработчик: AI Коллаборация &amp; C# WinUI Community.
        /// </summary>
        public static string AboutDev_Text {
            get {
                return ResourceManager.GetString("AboutDev.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Понятно.
        /// </summary>
        public static string AboutDialog_CloseButtonText {
            get {
                return ResourceManager.GetString("AboutDialog.CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Документация и руководство пользователя.
        /// </summary>
        public static string AboutDialog_Title {
            get {
                return ResourceManager.GetString("AboutDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fast WinUI 3 HEX Editor.
        /// </summary>
        public static string AboutTitle_Text {
            get {
                return ResourceManager.GetString("AboutTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия: 1.0.0 (Стабильный релиз).
        /// </summary>
        public static string AboutVersion_Text {
            get {
                return ResourceManager.GetString("AboutVersion.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Открытие:.
        /// </summary>
        public static string ManualSect1_1_Text {
            get {
                return ResourceManager.GetString("ManualSect1_1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Через меню &apos;Файл -&gt; Открыть файл...&apos; вы можете выбрать любой документ. Каждый новый файл изолированно открывается в своей индивидуальной вкладке..
        /// </summary>
        public static string ManualSect1_2_Text {
            get {
                return ResourceManager.GetString("ManualSect1_2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Закрытие:.
        /// </summary>
        public static string ManualSect1_3_Text {
            get {
                return ResourceManager.GetString("ManualSect1_3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажмите на крестик вкладки. Память дескриптора файла (FileStream) мгновенно освободится для операционной системы..
        /// </summary>
        public static string ManualSect1_4_Text {
            get {
                return ResourceManager.GetString("ManualSect1_4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1. РАБОТА С ФАЙЛАМИ И ВКЛАДКАМИ.
        /// </summary>
        public static string ManualSect1_Text {
            get {
                return ResourceManager.GetString("ManualSect1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Одиночный выбор:.
        /// </summary>
        public static string ManualSect2_1_Text {
            get {
                return ResourceManager.GetString("ManualSect2_1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Один клик ЛКМ (Левой Кнопкой Мыши) по ячейке выделяет байт. Его адрес дублируется в нижнем статус-баре..
        /// </summary>
        public static string ManualSect2_2_Text {
            get {
                return ResourceManager.GetString("ManualSect2_2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Выделение диапазона (Drag &amp; Drop):.
        /// </summary>
        public static string ManualSect2_3_Text {
            get {
                return ResourceManager.GetString("ManualSect2_3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зажмите ЛКМ на начальном байте и, не отпуская, ведите курсор через таблицу вверх или вниз. Сетка плавно подсветит выбранный массив. Правая кнопка мыши заблокирована для защиты от сброса выделения..
        /// </summary>
        public static string ManualSect2_4_Text {
            get {
                return ResourceManager.GetString("ManualSect2_4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2. МНОЖЕСТВЕННОЕ ВЫДЕЛЕНИЕ БАЙТОВ.
        /// </summary>
        public static string ManualSect2_Text {
            get {
                return ResourceManager.GetString("ManualSect2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Вход в режим редактирования:.
        /// </summary>
        public static string ManualSect3_1_Text {
            get {
                return ResourceManager.GetString("ManualSect3_1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двойной клик (Double Tap) по байту переводит ячейку в фокус ввода..
        /// </summary>
        public static string ManualSect3_2_Text {
            get {
                return ResourceManager.GetString("ManualSect3_2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Процесс посимвольной печати:.
        /// </summary>
        public static string ManualSect3_3_Text {
            get {
                return ResourceManager.GetString("ManualSect3_3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вводите HEX-символы [0-9] или [A-F]. При нажатии первой клавиши байт перейдет в полу-ввод (например, &apos;A?&apos;). Второе нажатие запишет байт окончательно, обновит его ASCII-символ справа, подсветит текст КРАСНЫМ цветом и автоматически переведет курсор на следующий шаг..
        /// </summary>
        public static string ManualSect3_4_Text {
            get {
                return ResourceManager.GetString("ManualSect3_4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Отмена и навигация:.
        /// </summary>
        public static string ManualSect3_5_Text {
            get {
                return ResourceManager.GetString("ManualSect3_5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажатие клавиши Escape сбрасывает режим редактирования ячейки. Перемещаться между ячейками во время ввода можно стрелочками на клавиатуре..
        /// </summary>
        public static string ManualSect3_6_Text {
            get {
                return ResourceManager.GetString("ManualSect3_6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3. ПОБАЙТОВОЕ РЕДАКТИРОВАНИЕ.
        /// </summary>
        public static string ManualSect3_Text {
            get {
                return ResourceManager.GetString("ManualSect3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Как использовать редактор:.
        /// </summary>
        public static string ManualTitle_Text {
            get {
                return ResourceManager.GetString("ManualTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе и руководство....
        /// </summary>
        public static string MenuAbout_Text {
            get {
                return ResourceManager.GetString("MenuAbout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать.
        /// </summary>
        public static string MenuCopy_Text {
            get {
                return ResourceManager.GetString("MenuCopy.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правка.
        /// </summary>
        public static string MenuEdit_Title {
            get {
                return ResourceManager.GetString("MenuEdit.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл.
        /// </summary>
        public static string MenuFile_Title {
            get {
                return ResourceManager.GetString("MenuFile.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти к адресу....
        /// </summary>
        public static string MenuGoTo_Text {
            get {
                return ResourceManager.GetString("MenuGoTo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка.
        /// </summary>
        public static string MenuHelp_Title {
            get {
                return ResourceManager.GetString("MenuHelp.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация о файле.
        /// </summary>
        public static string MenuInfo_Text {
            get {
                return ResourceManager.GetString("MenuInfo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть файл....
        /// </summary>
        public static string MenuOpen_Text {
            get {
                return ResourceManager.GetString("MenuOpen.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вставить.
        /// </summary>
        public static string MenuPaste_Text {
            get {
                return ResourceManager.GetString("MenuPaste.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string MenuSave_Text {
            get {
                return ResourceManager.GetString("MenuSave.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск по файлу.
        /// </summary>
        public static string MenuSearch_Text {
            get {
                return ResourceManager.GetString("MenuSearch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вид.
        /// </summary>
        public static string MenuView_Title {
            get {
                return ResourceManager.GetString("MenuView.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        public static string PivotAbout_Header {
            get {
                return ResourceManager.GetString("PivotAbout.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полный справочник функций.
        /// </summary>
        public static string PivotManual_Header {
            get {
                return ResourceManager.GetString("PivotManual.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выделено: {1} байт.
        /// </summary>
        public static string StatusBytesText {
            get {
                return ResourceManager.GetString("StatusBytesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смещение: {0}.
        /// </summary>
        public static string StatusOffsetText {
            get {
                return ResourceManager.GetString("StatusOffsetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер: {0:N0} байт.
        /// </summary>
        public static string StatusSizeText {
            get {
                return ResourceManager.GetString("StatusSizeText", resourceCulture);
            }
        }
    }
}
